Repository genexuslabs/gxserver-client, pull requests merged in 2022-03, with the labels that each got.

#4 XML External Entity (XXE) Prevention
  src/main/java/com/genexus/gxserver/client/helpers/DocumentBuilders.java
  src/main/java/com/genexus/gxserver/client/helpers/XmlHelper.java
Labels: fix

#5 ServerHelperClient does not require authentication
  src/main/java/com/genexus/gxserver/client/clients/BaseClient.java
  src/main/java/com/genexus/gxserver/client/clients/ServerHelperClient.java
  src/test/java/com/genexus/gxserver/client/clients/ServerHelperClientTest.java
Labels: bug

#14 Add auth token
  .github/workflows/integration.yml
  src/main/java/com/genexus/gxserver/client/clients/BaseClient.java
  src/main/java/com/genexus/gxserver/client/clients/TeamWorkService2Client.java
  src/main/java/com/genexus/gxserver/client/clients/common/ServiceData.java
  src/test/java/com/genexus/gxserver/client/clients/ServerData.java
  src/test/java/com/genexus/gxserver/client/clients/ServerHelperClientTest.java
  src/test/java/com/genexus/gxserver/client/clients/TeamWorkService2ClientTest.java
Labels: feature
